#!/bin/bash
# source: https://www.danielecook.com/generate-fasta-sequence-lengths/
file="$1"
[ "$file" == "-" ] && unset file
awk '$0 ~ ">" {if (NR > 1) {print c;} c=0;printf substr($0,2,100) "\t"; } $0 !~ ">" {c+=length($0);} END { print c; }' < "${file:-/dev/stdin}"
